backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD'}
      - { label: 'Body', name: 'body', widget: 'markdown' }